### ISSUE TITLE
Blank screen after signing in

### ISSUE THREAD

**Issue by chrismessina** [pontusab/Fastlane#1]
After signing in for the first time, I was greeted with this blank screen:

![screenshot_4_11_16__10_35_am](https://cloud.githubusercontent.com/assets/22610/14436386/48b5f6a2-ffd1-11e5-8e4e-397f148e2b3e.png)

I quit the app and restarted it, and upon launch, got a request to Allow Network Access, which is weird because I was able to load the sign in screen the first time I launched it. I allowed access and then I had to sign in again.

**Comment by pontusab** [comment]
I will look into that, did you manage to login after restart the second time?

**Comment by pontusab** [comment]
There will be some code refactoring and bug fixing to the stable release on App Store, this is great to get feedback from real users because it´s hard for me to test everything with different kind of perspectives :)

**Comment by pontusab** [comment]
Thanks for the info, this is great to make the app final and ready for a stable version on App store :+1:

**Comment by chrismessina** [comment]
Yes
