### ISSUE TITLE
Can't sign in

### ISSUE THREAD

**Issue by esttorhe** [pontusab/Fastlane#4]
Worth noting 2 things regarding log in:
1. Can't copy/paste my password. I use `1Password` and my passwords are 50 characters long with random alphanumeric strings and not being able to copy/paste is hard
2. After typing the password it keeps failing saying that either my email and/or password are wrong. Already tried 5 times and double checked that password and email match.

Also thanks for a brilliant idea 💡

**Comment by pontusab** [comment]
Thanks for the feedback, I will add support for copy & paste in next release.
About the password and email issue, you actually logging in at Ubers website so if thats wrong It should be your credentials..

**Comment by esttorhe** [comment]
yeah I checked the repo and noticed that its the website.

I'll have to check if my `1Password` stored a messed up password and will regenerate it but will wait to test it with `Fastlane` until after copy/paste is there; otherwise i could be the one messing the password.

Thanks :)

**Comment by pontusab** [comment]
Great :) I will add copy & paste to feature request :+1:  Will close this issue for now.
